name: release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: softprops/action-gh-release@v1
        with:
          body: |
            ## Installation

            #### Pre-Built Binaries

            Pre-built `colslc` and `rowslc` binaries compiled for various target platforms can be found under the [Releases](https://github.com/jace-ys/inslice/releases) section of this repository.

            #### Cargo

            To install `colslc` and `rowslc` using the `cargo` toolchain:

            ```shell
            cargo install inslice --version ${{ steps.tag.outputs.VERSION }}
            ```
          files: |
            README.md
            LICENSE

  github-publish:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/upload-rust-binary-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bin: colslc
          archive: inslice-$bin-$tag-$target
      - uses: taiki-e/upload-rust-binary-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bin: rowslc
          archive: inslice-$bin-$tag-$target

  cratesio-publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-inslice-${{ hashFiles('Cargo.toml') }}
          restore-keys: ${{ runner.os }}-inslice-
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CRATESIO_TOKEN }}
